<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.1 setup script
 * Date: Fri, 25 May 2018 11:00:07 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '@Iyaloo4189';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'n&p%E5;|8vvql>[Gys$;`Q69p&5w-esM';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>